"""
Pydantic schemas for Phase 2: Transcript-Only Gemini Hypothesis Agent (Agent #1).
"""

from typing import List, Literal, Optional, Dict, Any
from pydantic import BaseModel, Field


class FailureCase(BaseModel):
    """
    Transcript-only record of a target model failure.
    Contains NO internal activations, NO intervention results, and NO hidden test data.
    """
    case_id: str = Field(..., description="Unique case identifier (e.g. case_001)")
    task_description: str = Field(..., description="High-level description of task intended for target model")
    prompt: str = Field(..., description="Original user prompt given to target model")
    model_response: str = Field(..., description="Actual unexpected or incorrect response generated by target model")
    failure_description: str = Field(..., description="Short explanation of what went wrong or why response failed")
    expected_behavior: str = Field(..., description="Description of correct expected output")


class Hypothesis(BaseModel):
    """
    A single falsifiable causal hypothesis generated by Agent #1.
    """
    claim: str = Field(
        ..., 
        description="One-sentence falsifiable causal claim explaining the failure"
    )
    mechanism_guess: str = Field(
        ..., 
        description="Specific suspected mechanism (representations, layers, attention patterns, lexical features, token persistence)"
    )
    confidence: Literal["high", "medium", "low"] = Field(
        ..., 
        description="Agent confidence level based purely on transcript evidence"
    )


class HypothesisSet(BaseModel):
    """
    Structured output schema for Agent #1 hypothesis generation.
    Must contain 2 to 3 distinct hypotheses.
    """
    hypotheses: List[Hypothesis] = Field(
        ..., 
        min_length=2, 
        max_length=3, 
        description="List of 2 to 3 competing falsifiable hypotheses"
    )
    most_likely: int = Field(
        ..., 
        ge=1, 
        le=3, 
        description="1-indexed identifier of the hypothesis considered most likely by Agent #1"
    )


class Agent1GenerationRecord(BaseModel):
    """Complete logged record of an Agent #1 hypothesis generation run (Credentials omitted)."""
    case_id: str
    model_name: str
    sdk_version: str
    timestamp: str
    input_case: FailureCase
    hypothesis_set: HypothesisSet
    generation_config: Dict[str, Any]
