"""
Pydantic schemas for Phase 3A: Causal Investigator Agent (Agent #2) & Investigation Sandbox.
"""

from typing import List, Literal, Optional, Dict, Any
from pydantic import BaseModel, Field
from config import DEFAULT_INVESTIGATOR_MODEL


class InvestigationBudget(BaseModel):
    """Configuration and usage tracker for Agent #2 investigation budget."""
    max_experiments: int = Field(default=25, description="Maximum total experiments per investigation case")
    max_target_calls: int = Field(default=75, description="Maximum total target model forward runs")
    max_interventions: int = Field(default=40, description="Maximum activation interventions (patching/ablation)")
    
    experiments_used: int = Field(default=0, description="Experiments executed so far")
    target_calls_used: int = Field(default=0, description="Target model inference calls executed so far")
    interventions_used: int = Field(default=0, description="Activation interventions executed so far")

    def is_exhausted(self) -> bool:
        return (
            self.experiments_used >= self.max_experiments or
            self.target_calls_used >= self.max_target_calls or
            self.interventions_used >= self.max_interventions
        )


class ExperimentRequest(BaseModel):
    """Structured experiment request generated by Agent #2."""
    experiment_id: str = Field(..., description="Unique experiment identifier (e.g. exp_001)")
    hypothesis_id: int = Field(..., description="1-indexed ID of the hypothesis being tested")
    experiment_type: Literal[
        "run_target", 
        "capture", 
        "patch", 
        "ablate", 
        "compare",
        "tokenize_prompt",
        "attribution",
        "patch_head",
        "ablate_head",
        "patch_mlp",
        "ablate_mlp",
        "layer_sweep",
        "position_sweep",
        "patch_sweep",
        "dose_response",
        "random_control",
        "contrastive_control",
        "bidirectional_patch",
        "replicate"
    ] = Field(..., description="Explicit tool operation type")
    prompt: str = Field(..., description="Primary prompt given to target model")
    source_prompt: Optional[str] = Field(default=None, description="Source prompt for activation patching")
    control_prompt: Optional[str] = Field(default=None, description="Control prompt for contrastive control experiments")
    layer_idx: Optional[int] = Field(default=None, description="Target transformer layer index (0 to 25)")
    head_idx: Optional[int] = Field(default=None, description="Target attention head index (0 to 15)")
    position_idx: Optional[int] = Field(default=None, description="Target token position index")
    target_position_idx: Optional[int] = Field(default=None, description="Target prompt position index for patching")
    start_layer: Optional[int] = Field(default=None, description="Start layer index for layer sweep")
    end_layer: Optional[int] = Field(default=None, description="End layer index for layer sweep")
    step_layer: Optional[int] = Field(default=None, description="Step size for layer sweep")
    start_pos: Optional[int] = Field(default=None, description="Start token position for position sweep")
    end_pos: Optional[int] = Field(default=None, description="End token position for position sweep")
    alpha: Optional[float] = Field(default=None, description="Interpolation coefficient alpha for dose response (0.0 to 1.0)")
    control_type: Optional[str] = Field(default=None, description="Control type: 'none', 'random', 'contrastive'")
    replication_of_experiment_id: Optional[str] = Field(default=None, description="Experiment ID to replicate")
    expected_outcomes: Optional[List[str]] = Field(default=None, description="Expected outcome hypotheses for information gain calculation")
    candidate_tokens: Optional[List[str]] = Field(default=None, description="Candidate token strings to measure log-probabilities for")
    rationale: str = Field(..., description="Agent #2 reasoning for why this experiment discriminates the hypothesis")


class ExperimentProposalSet(BaseModel):
    """Structured collection of proposed experiments generated by Agent #2."""
    proposals: List[ExperimentRequest] = Field(..., description="List of proposed activation intervention experiments")


class ExperimentResult(BaseModel):
    """Immutable structured record of a completed target model experiment."""
    investigation_id: str = Field(..., description="Parent investigation case ID")
    experiment_id: str = Field(..., description="Unique experiment identifier")
    hypothesis_id: int = Field(..., description="Hypothesis tested")
    experiment_type: str = Field(..., description="Tool operation type executed")
    prompt: str = Field(..., description="Prompt used")
    source_prompt: Optional[str] = Field(default=None, description="Source prompt if patching")
    layer_idx: Optional[int] = Field(default=None, description="Layer index intervened on")
    head_idx: Optional[int] = Field(default=None, description="Attention head index intervened on")
    position_idx: Optional[int] = Field(default=None, description="Token position index")
    control_type: Optional[str] = Field(default=None, description="Control type ('none', 'random', 'contrastive')")
    replication_of_experiment_id: Optional[str] = Field(default=None, description="ID of replicated experiment")
    information_gain_estimate: Optional[float] = Field(default=None, description="Expected information gain estimate E[IG]")
    stopping_reason: Optional[str] = Field(default=None, description="Stopping reason if this experiment halted investigation")
    expected_outcomes: Optional[List[str]] = Field(default=None, description="Expected outcomes predicted before execution")
    
    baseline_output: str = Field(..., description="Observable model baseline output without intervention")
    intervened_output: Optional[str] = Field(default=None, description="Observable model output after intervention")
    
    activation_shape: Optional[List[int]] = Field(default=None, description="Tensor shape of captured/modified activation")
    activation_l2_norm: Optional[float] = Field(default=None, description="L2 norm of target activation tensor")
    patch_delta_norm: Optional[float] = Field(default=None, description="L2 norm of activation delta")
    observed_behavioral_delta: float = Field(default=0.0, description="Quantitative behavioral shift score")
    candidate_logprobs: Optional[Dict[str, float]] = Field(
        default=None, 
        description="Next-token log-probabilities for candidate answer tokens (e.g. {'Rome': -0.12, 'Paris': -8.45})"
    )
    candidate_delta_logprobs: Optional[Dict[str, float]] = Field(
        default=None,
        description="Delta in candidate logprobs (intervened - baseline)"
    )
    candidate_margin_delta: float = Field(
        default=0.0,
        description="Delta in candidate logprob margin: (logP(cand0) - logP(cand1))_intervened - (logP(cand0) - logP(cand1))_baseline"
    )
    effect_size: float = Field(
        default=0.0,
        description="Normalized effect size based on logprob margin shift or behavioral edit distance"
    )
    token_alignment: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Tokenizer mapping position index to token text"
    )
    attribution_scores: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Attribution / localization gradient-activation scores per layer/position"
    )
    sweep_results: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Detailed list of sweep step records"
    )
    dose_response_curve: Optional[Dict[str, float]] = Field(
        default=None,
        description="Mapping from stringified alpha to candidate_margin_delta for dose response"
    )
    
    evidence_type: Literal["observational", "intervention", "mechanism_discriminating"] = Field(
        default="observational",
        description="Classification of evidence type (observational vs residual intervention vs mechanism-discriminating)"
    )
    evidence_strength: Literal["weak", "moderate", "strong"] = Field(
        default="weak",
        description="Strength of evidence relative to specific mechanism hypothesis"
    )

    timestamp: str = Field(..., description="ISO 8601 execution timestamp")
    target_model_name: str = Field(default="google/gemma-2-2b-it", description="Target model ID")
    investigator_model_name: str = Field(default=DEFAULT_INVESTIGATOR_MODEL, description="Investigator model ID")


class HypothesisEvidence(BaseModel):
    """State tracking of evidence for a specific Agent #1 hypothesis."""
    hypothesis_id: int = Field(..., description="1-indexed hypothesis identifier")
    claim: str = Field(..., description="Original hypothesis claim")
    mechanism_guess: str = Field(..., description="Original mechanism guess")
    prior_confidence: str = Field(..., description="Prior confidence from Agent #1 ('high', 'medium', 'low')")
    
    supporting_experiments: List[str] = Field(default_factory=list, description="List of experiment IDs supporting representation relevance")
    contradicting_experiments: List[str] = Field(default_factory=list, description="List of experiment IDs weakening hypothesis")
    
    evidence_type: Literal["observational", "intervention", "mechanism_discriminating"] = Field(
        default="intervention",
        description="Primary evidence class gathered so far"
    )
    evidence_strength: Literal["weak", "moderate", "strong"] = Field(
        default="weak",
        description="Assessed strength of evidence specifically regarding component mechanism"
    )
    
    updated_confidence: Literal["high", "medium", "low"] = Field(..., description="Updated confidence after experimental evidence")
    status: Literal["unsupported", "weakly_supported", "supported", "contradicted", "unresolved", "mechanism_discriminating"] = Field(
        ..., description="Evidence status ('unsupported', 'weakly_supported', 'supported', 'contradicted', 'unresolved', 'mechanism_discriminating')"
    )
    max_margin_delta: float = Field(
        default=0.0,
        description="Maximum observed candidate margin delta across experiments"
    )
    rationale: str = Field(..., description="Scientifically conservative justification of evidence relevance and limits")


class InvestigationRecord(BaseModel):
    """Complete logged record of a Phase 3A Agent #2 investigation."""
    investigation_id: str
    case_id: str
    target_model_name: str = "google/gemma-2-2b-it"
    investigator_model_name: str = DEFAULT_INVESTIGATOR_MODEL
    timestamp: str
    state: Literal["INVESTIGATION", "BLIND_PREDICTION"] = Field(default="INVESTIGATION", description="Epistemic lifecycle state")
    stopping_reason: Optional[str] = Field(default=None, description="Reason for stopping investigation loop")
    budget_status: InvestigationBudget
    experiments: List[ExperimentResult] = Field(default_factory=list)
    hypothesis_evidence: List[HypothesisEvidence] = Field(default_factory=list)
    final_mechanistic_summary: Optional[str] = Field(default=None, description="Agent #2 final synthesis of causal intervention evidence")

