"""
Pydantic schemas for Phase 3A: Causal Investigator Agent (Agent #2) & Investigation Sandbox.
"""

from typing import List, Literal, Optional, Dict, Any
from pydantic import BaseModel, Field


class InvestigationBudget(BaseModel):
    """Configuration and usage tracker for Agent #2 investigation budget."""
    max_experiments: int = Field(default=5, description="Maximum total experiments per investigation case")
    max_target_calls: int = Field(default=15, description="Maximum total target model forward runs")
    max_interventions: int = Field(default=8, description="Maximum activation interventions (patching/ablation)")
    
    experiments_used: int = Field(default=0, description="Experiments executed so far")
    target_calls_used: int = Field(default=0, description="Target model inference calls executed so far")
    interventions_used: int = Field(default=0, description="Activation interventions executed so far")

    def is_exhausted(self) -> bool:
        return (
            self.experiments_used >= self.max_experiments or
            self.target_calls_used >= self.max_target_calls or
            self.interventions_used >= self.max_interventions
        )


class ExperimentRequest(BaseModel):
    """Structured experiment request generated by Agent #2."""
    experiment_id: str = Field(..., description="Unique experiment identifier (e.g. exp_001)")
    hypothesis_id: int = Field(..., description="1-indexed ID of the hypothesis being tested")
    experiment_type: Literal["run_target", "capture", "patch", "ablate", "compare"] = Field(
        ..., description="Explicit tool operation type"
    )
    prompt: str = Field(..., description="Primary prompt given to target model")
    source_prompt: Optional[str] = Field(default=None, description="Source prompt for activation patching")
    layer_idx: Optional[int] = Field(default=None, description="Target transformer layer index (0 to 25)")
    position_idx: Optional[int] = Field(default=None, description="Target token position index")
    target_position_idx: Optional[int] = Field(default=None, description="Target prompt position index for patching")
    candidate_tokens: Optional[List[str]] = Field(default=None, description="Candidate token strings to measure log-probabilities for")
    rationale: str = Field(..., description="Agent #2 reasoning for why this experiment discriminates the hypothesis")


class ExperimentResult(BaseModel):
    """Immutable structured record of a completed target model experiment."""
    investigation_id: str = Field(..., description="Parent investigation case ID")
    experiment_id: str = Field(..., description="Unique experiment identifier")
    hypothesis_id: int = Field(..., description="Hypothesis tested")
    experiment_type: str = Field(..., description="Tool operation type executed")
    prompt: str = Field(..., description="Prompt used")
    source_prompt: Optional[str] = Field(default=None, description="Source prompt if patching")
    layer_idx: Optional[int] = Field(default=None, description="Layer index intervened on")
    position_idx: Optional[int] = Field(default=None, description="Token position index")
    
    baseline_output: str = Field(..., description="Observable model baseline output without intervention")
    intervened_output: Optional[str] = Field(default=None, description="Observable model output after intervention")
    
    activation_shape: Optional[List[int]] = Field(default=None, description="Tensor shape of captured/modified activation")
    activation_l2_norm: Optional[float] = Field(default=None, description="L2 norm of target activation tensor")
    patch_delta_norm: Optional[float] = Field(default=None, description="L2 norm of activation delta")
    observed_behavioral_delta: float = Field(default=0.0, description="Quantitative behavioral shift score")
    candidate_logprobs: Optional[Dict[str, float]] = Field(
        default=None, 
        description="Next-token log-probabilities for candidate answer tokens (e.g. {'Rome': -0.12, 'Paris': -8.45})"
    )
    
    evidence_type: Literal["observational", "intervention", "mechanism_discriminating"] = Field(
        default="observational",
        description="Classification of evidence type (observational vs residual intervention vs mechanism-discriminating)"
    )
    evidence_strength: Literal["weak", "moderate", "strong"] = Field(
        default="weak",
        description="Strength of evidence relative to specific mechanism hypothesis"
    )

    timestamp: str = Field(..., description="ISO 8601 execution timestamp")
    target_model_name: str = Field(default="google/gemma-2-2b-it", description="Target model ID")
    investigator_model_name: str = Field(default="gemini-3.8-flash", description="Investigator model ID")


class HypothesisEvidence(BaseModel):
    """State tracking of evidence for a specific Agent #1 hypothesis."""
    hypothesis_id: int = Field(..., description="1-indexed hypothesis identifier")
    claim: str = Field(..., description="Original hypothesis claim")
    mechanism_guess: str = Field(..., description="Original mechanism guess")
    prior_confidence: str = Field(..., description="Prior confidence from Agent #1 ('high', 'medium', 'low')")
    
    supporting_experiments: List[str] = Field(default_factory=list, description="List of experiment IDs supporting representation relevance")
    contradicting_experiments: List[str] = Field(default_factory=list, description="List of experiment IDs weakening hypothesis")
    
    evidence_type: Literal["observational", "intervention", "mechanism_discriminating"] = Field(
        default="intervention",
        description="Primary evidence class gathered so far"
    )
    evidence_strength: Literal["weak", "moderate", "strong"] = Field(
        default="weak",
        description="Assessed strength of evidence specifically regarding component mechanism"
    )
    
    updated_confidence: Literal["high", "medium", "low"] = Field(..., description="Updated confidence after experimental evidence")
    status: Literal["supported", "weakened", "unresolved"] = Field(..., description="Evidence status ('supported', 'weakened', 'unresolved')")
    rationale: str = Field(..., description="Scientifically conservative justification of evidence relevance and limits")


class InvestigationRecord(BaseModel):
    """Complete logged record of a Phase 3A Agent #2 investigation."""
    investigation_id: str
    case_id: str
    target_model_name: str = "google/gemma-2-2b-it"
    investigator_model_name: str = "gemini-3.8-flash"
    timestamp: str
    budget_status: InvestigationBudget
    experiments: List[ExperimentResult] = Field(default_factory=list)
    hypothesis_evidence: List[HypothesisEvidence] = Field(default_factory=list)
    final_mechanistic_summary: Optional[str] = Field(default=None, description="Agent #2 final synthesis of causal intervention evidence")
