"""
Pydantic schemas for Phase 1: Causal Activation Patching Primitive.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class TokenAlignment(BaseModel):
    """Explicit token alignment details for source and target positions."""
    position_index: int = Field(..., description="0-indexed position within sequence")
    token_id: int = Field(..., description="Vocabulary token ID")
    token_str: str = Field(..., description="Decoded token string representation")
    sequence_length: int = Field(..., description="Total length of token sequence")


class BehavioralMeasurement(BaseModel):
    """Structured measurement of target model behavior."""
    generated_text: str = Field(..., description="Full text generated by model")
    new_tokens_text: str = Field(..., description="Newly generated tokens text")
    candidate_logprobs: Optional[Dict[str, float]] = Field(
        default=None, 
        description="Log-probabilities for specific candidate tokens (e.g. {'Paris': -0.12, 'Rome': -8.45})"
    )
    top_predicted_token: Optional[str] = Field(default=None, description="Most likely next token string")


class PatchingExperimentResult(BaseModel):
    """Structured result for a single activation patching experiment."""
    experiment_id: str = Field(..., description="Unique identifier for experiment run")
    model_name: str = Field(..., description="Target model ID (google/gemma-2-2b-it)")
    layer: int = Field(..., description="Transformer layer index patched")
    
    # Prompts & Token Alignments
    source_prompt: str = Field(..., description="Source prompt text (Prompt A)")
    target_prompt: str = Field(..., description="Target prompt text (Prompt B)")
    source_token: TokenAlignment = Field(..., description="Source token alignment info")
    target_token: TokenAlignment = Field(..., description="Target token alignment info")
    
    # Behavioral Outputs
    source_behavior: BehavioralMeasurement = Field(..., description="Baseline behavior on Source Prompt A")
    target_baseline_behavior: BehavioralMeasurement = Field(..., description="Baseline behavior on Target Prompt B (Control 1)")
    patched_behavior: BehavioralMeasurement = Field(..., description="Patched behavior on Target Prompt B (Control 2)")
    random_control_behavior: BehavioralMeasurement = Field(..., description="Norm-matched random control behavior on Target Prompt B (Control 3)")
    
    # Tensor Metrics
    activation_shape: List[int] = Field(..., description="Captured residual tensor shape [1, 1, hidden_dim]")
    activation_l2_norm: float = Field(..., description="L2 norm of captured source activation tensor")
    patch_delta_norm: float = Field(..., description="L2 norm of difference between target baseline tensor and source tensor")
    random_delta_norm: float = Field(..., description="L2 norm of difference between target baseline tensor and random control tensor")
    
    # Diagnostic Indicators
    behavioral_movement_toward_source: float = Field(
        ..., 
        description="Quantitative movement score toward source behavior (e.g., logprob shift of source label)"
    )
    random_movement_toward_source: float = Field(
        ..., 
        description="Quantitative movement score for random control"
    )
    is_specific_causal_effect: bool = Field(
        ..., 
        description="True if patched movement is significant AND random control does NOT mirror movement"
    )
    execution_success: bool = Field(default=True, description="True if forward passes completed without error")
    
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata (versions, seed, device, dtype)")


class LayerSweepResult(BaseModel):
    """Aggregate result for a layer sweep across transformer layers."""
    model_name: str
    source_prompt: str
    target_prompt: str
    target_layer_indices: List[int]
    results_by_layer: Dict[int, PatchingExperimentResult]
    best_causal_layer: Optional[int] = None
    summary_plot_ascii: Optional[str] = None
